# Generated by Django 5.2.7 on 2025-10-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='district',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='clinic',
            old_name='facility_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='guidancequery',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='guidancequery',
            old_name='question',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='created_at',
            new_name='date_subscribed',
        ),
        migrations.RenameField(
            model_name='symptomreport',
            old_name='created_at',
            new_name='date_reported',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='symptomreport',
            name='location',
        ),
        migrations.AddField(
            model_name='clinic',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default='2025-10-28 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptomreport',
            name='advice',
            field=models.TextField(default='Seek medical attention if symptoms persist.'),
            preserve_default=False,
        ),
    ]
